### ISSUE TITLE
suggest using Kotlin DSL rather than using groovy in Kotlin 

### ISSUE THREAD

**Issue by BLoHny** [hothuuk/Movie-Recommend#2]
https://blog.imqa.io/kotlin-dsl/
https://www.charlezz.com/?p=45140

Groovy의 사용이 단기적으로서는 build속도나 학습 곡선에서의 빠름이 잇겠지만
Kotlin Dsl의 장점이 장기적으로 더 좋다고 생각합니다.

**Comment by hothuuk** [comment]
의견 반영했습니다.
